### ISSUE TITLE
Request for Comment - iDeviceHacked

### ISSUE THREAD

**Issue by polymo1** [SideStore/anisette-servers#10]
@LucifersCircle 

Hello,

I noticed that your Anisette server has cloudflare proxying it.

Unfortunately, this makes it impossible to monitor status on our end, and could potentially cause trouble because cloudflare does not grant a special exception to SideStore clients.

I am giving you 2 options, unless you can think of a better one.

1. Remove your server from the list, for stability reasons.
2. Remove cloudflare's proxying from your ani. subdomain.

If you have any private comments or concerns, please reach out to me at wes@sidestore.io

Thanks!

Wesley Bryie

**Comment by LucifersCircle** [comment]
@polymo1 SideStore user agent is whitelisted from cf challenges in my waf settings. Is there a 3rd option where I can whitelist your monitoring service ua as well? If not then it's alright to remove my server, thanks.

**Comment by polymo1** [comment]
> @polymo1 SideStore user agent is whitelisted from cf challenges in my waf settings. Is there a 3rd option where I can whitelist your monitoring service ua as well? If not then it's alright to remove my server, thanks.

Gotcha, if you can add whatever Uptime Kuma uses, or white-list the IP for uptime.sidestore.io, that'll work. Thanks!

**Comment by LucifersCircle** [comment]
Should be good to go. Let me know if there's still an issue! Have a good evening!

**Comment by LucifersCircle** [comment]
Checked my logs after bed and saw it was still being blocked by bot-fight. I've made it skip that now!
