### ISSUE TITLE
1 Week Warning - SteX

### ISSUE THREAD

**Issue by polymo1** [SideStore/anisette-servers#9]
@Distancexx 

This is your one week warning to notify us of any further downtime, or in a week or less your anisette server could be removed from the official list.

If you have a valid reason for the server being down, and will be getting it back up ASAP, it can stay.

However, if there is not the likelihood if it coming back up soon, we will be removing it from the list.

You can email me at wes@sidestore.io if there are any private issues.

Thank you,

Wesley Bryie

**Comment by Distancexx** [comment]
The ssl certificate has expired. At present, it has been renewed and is working normally.

**Comment by polymo1** [comment]
Awesome, thanks! I recommend something like caddy or certbot going forward.
